services:
  # Backend Server
  nextai-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nextai-server
    env_file:
      - ../.env  # Uses your existing root .env file
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    volumes:
      - ../packages/server/uploads:/app/packages/server/uploads
      - ../packages/server/logs:/app/packages/server/logs
    ports:
      - "5001:5001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Application
  nextai-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: nextai-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - nextai-server
