export const INGREDIENT_SYNONYMS = {
  chicken: ["chicken", "chkn", "chikn", "pollo", "hen"],
  beef: ["beef", "steak", "sirloin", "brisket", "beefsteak"],
  pork: [
    "pork",
    "bacon",
    "ham",
    "prosciutto",
    "char siu",
    "bbq pork",
    "pepperoni",
  ],
  dairy: [
    "milk",
    "cheese",
    "butter",
    "cream",
    "yogurt",
    "mozzarella",
    "parmesan",
    "ricotta",
    "alfredo",
  ],
  egg: ["egg", "eggs", "omelet", "omelette", "mayo", "mayonnaise", "aioli"],
  shellfish: [
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "oyster",
    "clam",
    "mussel",
    "scallop",
  ],
  fish: [
    "fish",
    "salmon",
    "tuna",
    "cod",
    "tilapia",
    "trout",
    "sardine",
    "anchovy",
  ],
  gluten: [
    "bread",
    "bun",
    "pasta",
    "noodle",
    "ramen",
    "udon",
    "dumpling",
    "gyoza",
    "wonton",
    "flour",
    "tortilla",
    "batter",
    "wheat",
    "breadcrumbs",
    "soy sauce",
    "seitan",
  ],
  peanut: ["peanut", "groundnut", "satay"],
  nuts: ["almond", "cashew", "walnut", "pecan", "hazelnut", "pistachio", "nut"],
  alcohol: [
    "wine",
    "beer",
    "ale",
    "stout",
    "lager",
    "sake",
    "soju",
    "cooking wine",
  ],
};
